services:
  aquaflow-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aquaflow-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: AquaFlow123!
    ports:
      - "1435:1433"
    expose:
      - "1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  aquaflow-rabbitmq:
    image: rabbitmq:3-management
    container_name: aquaflow-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  sqlserver_data:
