version: '3.8'

services:
  aquaflow-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aquaflow-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: AquaFlow123!
    ports:
      - "1435:1433"
    expose:
      - "1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
